test_0 (__main__.lab2a.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for file creation: ./lab2a.py ... ok
test_1 (__main__.lab2a.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for errors running: ./lab2a.py ... /usr/lib/python3.12/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_2 (__main__.lab2a.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct shebang line: ./lab2a.py ... ok
test_3 (__main__.lab2a.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py ... ok
test_0 (__main__.lab2b.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - using input() function - Test for file creation: ./lab2b.py ... ok
test_1 (__main__.lab2b.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for errors with sending input "Jon" "20": ./lab2b.py ... ok
test_2 (__main__.lab2b.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for correct shebang line: ./lab2b.py ... ok
test_3 (__main__.lab2b.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jon" "20": ./lab2b.py ... FAIL

======================================================================
FAIL: test_3 (__main__.lab2b.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jon" "20": ./lab2b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmbenjamin/ops445/lab2/./CheckLab2.py", line 110, in test_3
    self.assertEqual(stdout, expected_output, msg=error_output)
AssertionError: b'Name: Jon\nAge: 20\nHi Jon, you are 20 years old.\n' != b'Name: Age: Hi Jon, you are 20 years old.\n' : output is not correct (HINT: pay attention to spelling, uppercase letters, spaces, and punctuation)

----------------------------------------------------------------------
Ran 8 tests in 0.047s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab2.py
=================================================================
    User login name: dmbenjamin
    Git Email: darianmikhail@gmail.com
    Linux system name: dmbenjamin-virtual-machine
    Python executable: /usr/bin/python3
    Python version:  3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
    OS Platform: linux
    Working Directory: /home/dmbenjamin/ops445/lab2
    Start at: Thu Jan 30 19:29:12 2025
=================================================================
